### ISSUE TITLE
Missleading docs for embedded Kotlin

### ISSUE THREAD

**Issue by jangalinski** [gradle/kotlin-dsl-docs#1]
In the current 5.4 docs, the section "embedded kotlin" states

> Gradle ships with kotlin-compiler-embeddable plus matching versions of kotlin-stdlib and kotlin-reflect libraries. For example, Gradle 4.3 ships with the Kotlin DSL v0.12.1 that includes Kotlin 1.1.51 versions of these modules. The kotlin package from those modules is visible through the Gradle classpath.

which per se is correct, but on a 5.4 docs page I would expect information on the current versions.

**Comment by eskatos** [comment]
Thanks for the report @jangalinski.
Those version numbers are _For example_.

Note that the documentation resides in the https://github.com/gradle/gradle repository.
If you feel strongly about this, please open an issue there, or even a pull-request?
